Repository effigy-se/effigy-se, pull requests merged in 2023-08, with the labels that each got.

#354 Foxhole & Mini - Lighting Fix
  _maps/map_files/FoxHoleStation/foxholestation.dmm
  _maps/map_files/MiniStation/MiniStation.dmm
Labels: Fix

#383 Nothing to see here citizen, move along.
  config/maps.txt
Labels: FUCK

#388 God Can't Stop Me; Catching Up Our SR Ports, Again
  code/__DEFINES/_effigy/keybindings.dm
  code/__DEFINES/_effigy/living.dm
  code/__DEFINES/_effigy/obj_flags.dm
  code/datums/keybinding/mob.dm
  code/modules/mob/mob_movement.dm
  code/modules/surgery/organ_manipulation.dm
  local/code/datums/components/damage_tracker.dm
  local/code/datums/components/interaction_components.dm
  local/code/datums/components/pixel_shift_component.dm
  local/code/datums/keybinding/mob.dm
  local/code/datums/loadout_manager.dm
  local/code/modules/client/preferences.dm
  local/code/modules/client/preferences/erp_preferences.dm
  local/code/modules/lewd/lewd_arousal/climax.dm
  local/code/modules/lewd/lewd_clothing/ballgag.dm
  local/code/modules/lewd/lewd_clothing/bdsm_mask.dm
  local/code/modules/lewd/lewd_clothing/corset.dm
  local/code/modules/lewd/lewd_clothing/deprivation_helmet.dm
  local/code/modules/lewd/lewd_clothing/kinky_sleepbag.dm
  local/code/modules/lewd/lewd_clothing/strapon.dm
  local/code/modules/lewd/lewd_helpers/misc.dm
  local/code/modules/lewd/lewd_helpers/pref_checking.dm
  local/code/modules/lewd/lewd_helpers/sounds.dm
  local/code/modules/lewd/lewd_items/_masturbation_item.dm
  local/code/modules/lewd/lewd_items/attachable_vibrator.dm
  local/code/modules/lewd/lewd_items/condom.dm
  local/code/modules/lewd/lewd_items/dildo.dm
  local/code/modules/lewd/lewd_items/feather.dm
  local/code/modules/lewd/lewd_items/fleshlight.dm
  local/code/modules/lewd/lewd_items/kinky_shocker.dm
  local/code/modules/lewd/lewd_items/leather_whip.dm
  local/code/modules/lewd/lewd_items/magic_wand.dm
  local/code/modules/lewd/lewd_items/shibari.dm
  local/code/modules/lewd/lewd_items/spanking_pad.dm
  local/code/modules/lewd/lewd_items/torture_candle.dm
  local/code/modules/lewd/lewd_items/vibrator.dm
  local/code/modules/lewd/lewd_items/vibroring.dm
  local/code/modules/lewd/lewd_structures/bdsm_furniture.dm
  local/code/modules/mob/living/layer_shift.dm
  local/code/modules/mob/living/living.dm
  local/code/modules/mob/living/living_movement.dm
  local/code/modules/mob/living/pixel_shift.dm
  local/code/modules/mob/mob.dm
  local/code/modules/modular_implants/soulcatcher/soulcatcher_component.dm
  local/code/modules/modular_implants/soulcatcher/soulcatcher_mob.dm
  local/code/modules/surgery/organs/genitals.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/skyrat/erp_preferences.tsx
Labels: Mirror/Port

#395 [PORT] Fixes Quickspawn/Human Transformation Eating Prefs
  code/modules/client/preferences.dm
  local/code/modules/client/preferences.dm
Labels: Fix, Test Merge Candidate, Mirror/Port

#391 Airlocks v2 (v2)
  local/code/datums/greyscale/greyscale_configs.dm
  local/code/datums/greyscale/json_configs/airlock/effigy_airlock_material.json
  local/code/datums/greyscale/json_configs/airlock/effigy_airlock_v2.json
  local/code/game/machinery/doors/airlock.dm
  local/icons/obj/doors/airlocks/effigy/effigy.dmi
  local/icons/obj/doors/airlocks/effigy/overlays.dmi
Labels: Feature, Test Merge Candidate

#419 [PORT] Fixes Quickspawn/SimpleTF/genetics eating mutcols
  code/modules/client/preferences.dm
  local/code/datums/dna.dm
  local/code/modules/client/preferences.dm
Labels: Fix, Mirror/Port
