Repository effigy-se/effigy-se, pull requests merged in 2023-10, with the labels that each got.

#476 NIF Purgatory - More Ports To NIFS, Soulcatchers, And... Other Things.
  code/__DEFINES/_effigy/nifsofts.dm
  code/__DEFINES/_effigy/traits.dm
  code/modules/mod/mod_link.dm
  code/modules/research/techweb/all_nodes.dm
  local/code/game/objects/items/devices/rsd_interface.dm
  local/code/modules/modular_implants/nif_persistence.dm
  local/code/modules/modular_implants/nif_research.dm
  local/code/modules/modular_implants/nifs.dm
  local/code/modules/modular_implants/nifs_tgui.dm
  local/code/modules/modular_implants/nifsoft_catalog.dm
  local/code/modules/modular_implants/nifsofts.dm
  local/code/modules/modular_implants/nifsofts/base_types/action_granter.dm
  local/code/modules/modular_implants/nifsofts/book_summoner.dm
  local/code/modules/modular_implants/nifsofts/dorms.dm
  local/code/modules/modular_implants/nifsofts/hypnosis.dm
  local/code/modules/modular_implants/nifsofts/prop_summoner.dm
  local/code/modules/modular_implants/nifsofts/scryer.dm
  local/code/modules/modular_implants/nifsofts/shapeshifter.dm
  local/code/modules/modular_implants/nifsofts/soulcatcher.dm
  local/code/modules/modular_implants/soulcatcher/attachble_soulcatcher.dm
  local/code/modules/modular_implants/soulcatcher/handheld_soulcatcher.dm
  local/code/modules/modular_implants/soulcatcher/soulcatcher_component.dm
  local/code/modules/modular_implants/soulcatcher/soulcatcher_mob.dm
  local/code/modules/modular_implants/soulcatcher/soulcatcher_tgui.dm
  local/code/modules/research/medical_designs.dm
  local/code/modules/vending/games.dm
  local/icons/hud/nifsoft.dmi
  local/icons/obj/devices.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/NifPanel.js
  tgui/packages/tgui/interfaces/NtosNifsoftCatalog.js
  tgui/packages/tgui/interfaces/Soulcatcher.js
  tgui/packages/tgui/interfaces/SoulcatcherUser.js
Labels: Feature, Mirror/Port

#480 [PORT] A tail of Australian Shepherd tails and Harpy Wings (new sprites)
  local/code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  local/code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  local/icons/obj/mob/mutant/mutant_accessories/tails.dmi
  local/icons/obj/mob/mutant/mutant_accessories/wings.dmi
Labels: Mirror/Port

#481 More Module Mirrors
  local/code/modules/lewd/lewd_clothing/bdsm_mask.dm
  local/code/modules/modular_implants/nifs_tgui.dm
  local/code/modules/modular_implants/nifsofts.dm
  local/code/modules/modular_implants/nifsofts/soul_poem.dm
  local/code/modules/modular_implants/nifsofts/soulcatcher.dm
  local/code/modules/modular_implants/soulcatcher/soulcatcher_component.dm
  local/code/modules/modular_implants/soulcatcher/soulcatcher_tgui.dm
  local/icons/mob/clothing/under/cargo.dmi
  local/icons/mob/clothing/under/cargo_digi.dmi
  tgui/packages/tgui/interfaces/NifSoulPoem.js
  tgui/packages/tgui/interfaces/Soulcatcher.js
Labels: Mirror/Port

#496 Two New Rimpoint Ruins
  _maps/RandomRuins/JungleRuins/generator_right_here.dmm
  _maps/RandomRuins/JungleRuins/trilogy.dmm
  config/jungleruinblacklist.txt
  local/code/datums/id_trim/ruins.dm
  local/code/datums/ruins/jungle.dm
  local/code/game/objects/effects/decals/turfdecal/markings.dm
  local/code/game/objects/items/toys.dm
  local/code/modules/mob_spawn/corpses/nanotrasen_corpses.dm
  local/icons/turf/decals.dmi
  tgstation.dme
Labels: Feature, Code Improvement, Config Update

#514 TG Update 75da480
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  code/__DEFINES/reagents.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/components/plumbing/reaction_chamber.dm
  code/datums/sprite_accessories.dm
  code/game/atoms.dm
  code/game/objects/structures/fluff.dm
  code/modules/client/preferences/species_features/basic.dm
  code/modules/clothing/head/wig.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/basic/space_fauna/ghost.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mod/modules/modules_security.dm
  code/modules/plumbing/plumbers/acclimator.dm
  code/modules/plumbing/plumbers/reaction_chamber.dm
  code/modules/plumbing/plumbers/synthesizer.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents/reaction_agents_reagents.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/head_hair_and_lips.dm
  code/modules/surgery/organs/external/tails.dm
  code/modules/zombie/organs.dm
  html/changelogs/AutoChangeLog-pr-78994.yml
  html/changelogs/archive/2023-10.yml
  icons/mob/human/human_face.dmi
  local/code/modules/mob/living/carbon/human/species.dm
  local/code/modules/mob/living/carbon/human/species_types/synthetic.dm
Labels: TG Update

#518 Opens The Gates Of Hades: Part One, Just The Ruin Datums
  code/datums/ruins/icemoon.dm
  code/datums/ruins/lavaland.dm
  code/datums/ruins/space.dm
Labels: Help Wanted, FUCK

#519 Allows ghost role static spawning
  code/modules/mob_spawn/mob_spawn.dm
  local/code/modules/mob_spawn/mob_spawn.dm
  tgstation.dme
Labels: Test Merge Candidate

#531 Ports a Fix To The Issue Of All Time
  local/code/modules/surgery/robot_healing.dm
Labels: FUCK, Mirror/Port

#533 Adjusted railings
  local/code/game/objects/structures/railings.dm
  local/icons/obj/railings.dmi
  tgstation.dme
Labels: Test Merge Candidate, Test Merge Only

#530 Adjust light intensity/range
  local/code/game/machinery/doors/firedoor.dm
  local/code/game/machinery/light.dm
Labels: Test Merge Candidate
