Repository effigy-se/effigy-se, pull requests merged in 2023-06, with the labels that each got.

#166 Video Killed The Radio Host - The Broadcast Team
  _maps/foxholestation.json
  _maps/map_files/FoxHoleStation/foxholestation.dmm
  _maps/ministation.json
  _maps/templates/automapper/automapper_config.toml
  _maps/templates/automapper/birdshot/birdshot_broadcast_studio.dmm
  _maps/templates/automapper/icebox/icebox_broadcast_studio.dmm
  _maps/templates/automapper/metastation/metastation_broadcast_studio.dmm
  _maps/templates/automapper/northstar/northstar_broadcast_studio.dmm
  _maps/templates/automapper/northstar/northstar_cryo.dmm
  _maps/templates/automapper/tramstation/tramstation_broadcast_studio.dmm
  code/__DEFINES/_effigy/access.dm
  code/__DEFINES/_effigy/atom_hud.dm
  code/__DEFINES/_effigy/jobs.dm
  code/__DEFINES/_effigy/radio.dm
  code/__DEFINES/access.dm
  code/datums/id_trim/jobs.dm
  code/game/communications.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/say.dm
  code/modules/mob/living/living_say.dm
  code/modules/mob/living/simple_animal/parrot.dm
  config/jobconfig.toml
  packages/broadcast_team/code/controllers/subsystem/id_access.dm
  packages/broadcast_team/code/datums/id_trim/jobs.dm
  packages/broadcast_team/code/game/area/areas/station.dm
  packages/broadcast_team/code/game/machinery/camera/camera.dm
  packages/broadcast_team/code/game/machinery/camera/presets.dm
  packages/broadcast_team/code/game/machinery/computer/camera.dm
  packages/broadcast_team/code/game/machinery/computer/telescreen.dm
  packages/broadcast_team/code/game/objects/effects/landmarks.dm
  packages/broadcast_team/code/game/objects/items/circuitboards/computer_circuitboards.dm
  packages/broadcast_team/code/game/objects/items/devices/radio/encryptionkey.dm
  packages/broadcast_team/code/game/objects/items/devices/radio/headset.dm
  packages/broadcast_team/code/game/objects/items/devices/radio/intercom.dm
  packages/broadcast_team/code/game/objects/structures/construction_console/construction_console.dm
  packages/broadcast_team/code/game/objects/structures/construction_console/construction_console_broadcast.dm
  packages/broadcast_team/code/modules/jobs/job_types/broadcast_team.dm
  packages/broadcast_team/code/modules/mapping/access_helpers.dm
  packages/broadcast_team/code/modules/modular_computers/computers/item/role_tablet_presets.dm
  packages/broadcast_team/icons/obj/card.dmi
  packages/gfx/airlock.dm
  packages/gfx/assets/obj/airlock/station/service.dmi
  packages/gfx/assets/obj/airlock/station/silver.dmi
  packages/gfx/assets/obj/airlock/station/studio.dmi
  packages/ux/assets/mob/hud.dmi
  tgstation.dme
Labels: Feature, Config Update, Test Merge Candidate

#189 TG Update f109d56
  SQL/database_changelog.md
  _maps/RandomRuins/IceRuins/icemoon_surface_bughabitat.dmm
  _maps/map_files/Birdshot/birdshot.dmm
  _maps/shuttles/whiteship_pubby.dmm
  code/__DEFINES/dcs/signals/signals_datum.dm
  code/_globalvars/phobias.dm
  code/datums/ai/basic_mobs/basic_subtrees/speech_subtree.dm
  code/datums/components/growth_and_differentiation.dm
  code/datums/memory/_memory.dm
  code/game/objects/items/food/egg.dm
  code/game/objects/items/weaponry.dm
  code/modules/cargo/packs/livestock.dm
  code/modules/holodeck/holo_effect.dm
  code/modules/mob/living/basic/farm_animals/chicken/chick.dm
  code/modules/mob/living/basic/farm_animals/chicken/chicken.dm
  code/modules/mob/living/basic/space_fauna/ant.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  html/changelogs/AutoChangeLog-pr-75662.yml
  html/changelogs/AutoChangeLog-pr-75663.yml
  html/changelogs/AutoChangeLog-pr-75785.yml
  html/changelogs/AutoChangeLog-pr-75796.yml
  html/changelogs/archive/2023-06.yml
  icons/mob/clothing/accessories.dmi
  icons/mob/clothing/back.dmi
  icons/mob/clothing/belt.dmi
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/neck.dmi
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/mob/inhands/weapons/axes_lefthand.dmi
  icons/mob/inhands/weapons/axes_righthand.dmi
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/suits/chaplain.dmi
  icons/obj/fireplace.dmi
  icons/obj/food/meat.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/kitchen.dmi
  icons/obj/lavaland/artefacts.dmi
  icons/obj/lavaland/elite_trophies.dmi
  icons/obj/lavaland/legionnaire_bonfire.dmi
  icons/obj/mining.dmi
  icons/obj/stack_objects.dmi
  icons/obj/storage/medkit.dmi
  icons/obj/weapons/fireaxe.dmi
  tgstation.dme
  tools/UpdatePaths/Scripts/75592_simple_to_basic_chickens.txt
  tools/UpdatePaths/Scripts/75662_simple_to_basic_ants.txt
Labels: TG Update

#185 Local Shark Systematically Tries To Get The Codebase To Pass Tests Again
  _maps/map_files/MiniStation/MiniStation.dmm
  _maps/templates/automapper/birdshot/birdshot_broadcast_studio.dmm
  packages/clothing/modular_glasses.dm
  packages/customization/modules/research/designs/misc_designs.dm
  packages/greyscale/greyscale_configs.dm
  packages/greyscale/json_configs/beret/beret_badge_fancy.json
  packages/greyscale/json_configs/beret/beret_badge_fancy_worn.json
  packages/teshari/teshari_clothes.dm
  tgstation.dme
Labels: FUCK

#193 [FUCK] Fixes Foxhole Explosions
  _maps/foxholestation.json
Labels: GBP: No Update, FUCK

#184 Wholesale SR NIF Port: (Featuring Soulcatchers From The Virgo Series)
  code/__DEFINES/_effigy/_organ_defines.dm
  code/__DEFINES/_effigy/nifsofts.dm
  code/__DEFINES/_effigy/signals.dm
  code/__HELPERS/mobs.dm
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/ticker.dm
  code/datums/components/mind_linker.dm
  code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
  code/game/objects/items/storage/belt.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/emote.dm
  code/modules/research/techweb/all_nodes.dm
  overrides/code/modules/client/preferences/brain.dm
  overrides/code/modules/clothing/suits/labcoat.dm
  packages/cryo/cryopod.dm
  packages/customization/assets/mob/actions/action_backgrounds.dmi
  packages/customization/assets/mob/actions/actions_nif.dmi
  packages/customization/assets/mob/actions/actions_slime.dmi
  packages/lewd/lewd_machinery/lustwish.dm
  packages/modular_implants/code/cargo/goodies.dm
  packages/modular_implants/code/misc_devices.dm
  packages/modular_implants/code/nif_actions.dm
  packages/modular_implants/code/nif_implants.dm
  packages/modular_implants/code/nif_persistence.dm
  packages/modular_implants/code/nif_research.dm
  packages/modular_implants/code/nifs.dm
  packages/modular_implants/code/nifs_tgui.dm
  packages/modular_implants/code/nifsoft_catalog.dm
  packages/modular_implants/code/nifsofts.dm
  packages/modular_implants/code/nifsofts/dorms.dm
  packages/modular_implants/code/nifsofts/hivemind.dm
  packages/modular_implants/code/nifsofts/money_sense.dm
  packages/modular_implants/code/nifsofts/prop_summoner.dm
  packages/modular_implants/code/nifsofts/shapeshifter.dm
  packages/modular_implants/code/nifsofts/soul_poem.dm
  packages/modular_implants/code/nifsofts/soulcatcher.dm
  packages/modular_implants/code/soulcatcher/handheld_soulcatcher.dm
  packages/modular_implants/code/soulcatcher/soulcatcher_body_component.dm
  packages/modular_implants/code/soulcatcher/soulcatcher_component.dm
  packages/modular_implants/code/soulcatcher/soulcatcher_mob.dm
  packages/modular_implants/code/soulcatcher/soulcatcher_tgui.dm
  packages/modular_implants/icons/chat.dmi
  packages/modular_implants/icons/obj/devices.dmi
  packages/modular_implants/icons/obj/disks.dmi
  packages/modular_implants/icons/obj/machines/vendors.dmi
  packages/modular_implants/icons/obj/nifs.dmi
  packages/modular_implants/sounds/default_bad.ogg
  packages/modular_implants/sounds/default_click.ogg
  packages/modular_implants/sounds/default_good.ogg
  packages/modular_persistence/README.md
  packages/modular_persistence/code/modular_persistence.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/NifPanel.js
  tgui/packages/tgui/interfaces/NifSoulPoem.js
  tgui/packages/tgui/interfaces/NtosNifsoftCatalog.js
  tgui/packages/tgui/interfaces/Soulcatcher.js
Labels: Feature, Test Merge Candidate

#217 [FUCK] (Genuinely) Half-"Fixes" #213
  packages/liquids/liquid_systems/liquid_effect.dm
Labels: Bug, FUCK

#230 [FUCK] Disables Tot Unit Test On Liquids Debug
  _maps/effigy_liquids.json
Labels: FUCK

#239 Updates airlock assembly sprites
  code/modules/asset_cache/assets/rcd.dm
  packages/gfx/airlock.dm
Labels: Fix

#248 Revert 243
  code/_onclick/cyborg.dm
  code/controllers/subsystem/processing/quirks.dm
  code/datums/bodypart_overlays/mutant_bodypart_overlay.dm
  local/code/_onclick/cyborg.dm
  local/code/controllers/subsystem/processing/quirks.dm
  local/code/datums/bodypart_overlays/mutant_bodypart_overlay.dm
  local/effigy_proc.dm
  local/local.md
  tgstation.dme
Labels: FUCK

#250 [FUCK] Fixes Some Dirt-On-Wall Action
  _maps/map_files/FoxHoleStation/foxholestation.dmm
  _maps/templates/automapper/metastation/metastation_broadcast_studio.dmm
Labels: FUCK

#249 Fixes pixel shift on stand up
  code/modules/mob/living/living.dm
Labels: Fix

#253 [FUCK] Foxhole Display Cases
  _maps/map_files/FoxHoleStation/foxholestation.dmm
Labels: GBP: No Update, FUCK, Oversight

#257 TG Update 0d25662 hotfix
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/structures/door_assembly.dm
Labels: TG Update

#258 Map reset
  _maps/map_files/Basketball/greytide_worldwide.dmm
  _maps/map_files/Basketball/lusty_xenomorphs.dmm
  _maps/map_files/Basketball/soviet_bear.dmm
  _maps/map_files/Birdshot/birdshot.dmm
  _maps/map_files/CTF/downtown.dmm
  _maps/map_files/CTF/turbine.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/NorthStar/north_star.dmm
  _maps/map_files/debug/multiz.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/tramstation/maintenance_modules/arrivallibraryupper_1.dmm
  _maps/map_files/tramstation/maintenance_modules/atmoscilower_attachment_a_3.dmm
  _maps/map_files/tramstation/maintenance_modules/dormenginelower_attachment_b_1.dmm
  _maps/map_files/tramstation/maintenance_modules/medsciupper_attachment_a_3.dmm
  _maps/map_files/tramstation/tramstation.dmm
Labels: FUCK
