Repository effigy-se/effigy-se, pull requests merged in 2023-11, with the labels that each got.

#567 Icebox Pool Fix, Rimpoint Water Fix
  _maps/templates/automapper/icebox/icebox_pool_surface.dmm
  local/code/game/turfs/open/water.dm
  tgstation.dme
Labels: Fix, FUCK

#565 Add Effigy's birthday
  local/code/modules/holiday/holidays.dm
  tgstation.dme
Labels: RED LABEL

#586 Fix TGUI
  tgui/packages/tgui/interfaces/CryopodConsole.jsx
  tgui/packages/tgui/interfaces/ExaminePanel.jsx
  tgui/packages/tgui/interfaces/LoadoutManager.jsx
  tgui/packages/tgui/interfaces/MilkingMachine.jsx
  tgui/packages/tgui/interfaces/NifPanel.jsx
  tgui/packages/tgui/interfaces/NifSoulPoem.jsx
  tgui/packages/tgui/interfaces/NtosNifsoftCatalog.jsx
  tgui/packages/tgui/interfaces/Signalvib.jsx
  tgui/packages/tgui/interfaces/Soulcatcher.jsx
  tgui/packages/tgui/interfaces/SoulcatcherUser.jsx
Labels: FUCK

#587 TG Update b22cb83
  code/datums/wires/airlock.dm
  code/game/area/areas/station/cargo.dm
  code/modules/research/designs/wiremod_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/wiremod/components/math/arctan2.dm
  html/changelogs/AutoChangeLog-pr-574.yml
  html/changelogs/archive/2023-11.yml
  icons/obj/machines/engine/supermatter.dmi
  tgstation.dme
  tgui/.eslintrc.yml
  tgui/packages/tgui-panel/chat/renderer.jsx
  tgui/packages/tgui-panel/index.jsx
  tgui/packages/tgui/interfaces/BountyBoard.tsx
  tgui/packages/tgui/interfaces/HotkeysHelp.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/QuirksPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
  tgui/packages/tgui/interfaces/QuantumConsole.tsx
  tgui/packages/tgui/interfaces/StackCrafting.tsx
  tgui/packages/tgui/interfaces/common/GasmixParser.tsx
  tgui/packages/tgui/stories/Blink.stories.jsx
  tgui/packages/tgui/stories/BlockQuote.stories.jsx
  tgui/packages/tgui/stories/Box.stories.jsx
  tgui/packages/tgui/stories/Button.stories.jsx
  tgui/packages/tgui/stories/ByondUi.stories.jsx
  tgui/packages/tgui/stories/Collapsible.stories.jsx
  tgui/packages/tgui/stories/Flex.stories.jsx
  tgui/packages/tgui/stories/Input.stories.jsx
  tgui/packages/tgui/stories/LabeledList.stories.jsx
  tgui/packages/tgui/stories/Popper.stories.jsx
  tgui/packages/tgui/stories/ProgressBar.stories.jsx
  tgui/packages/tgui/stories/Stack.stories.jsx
  tgui/packages/tgui/stories/Storage.stories.jsx
  tgui/packages/tgui/stories/Tabs.stories.jsx
  tgui/packages/tgui/stories/Themes.stories.jsx
  tgui/packages/tgui/stories/Tooltip.stories.jsx
  tgui/packages/tgui/stories/common.jsx
Labels: TG Update

#589 TG Update 878c5a5
  icons/obj/machines/wallmounts.dmi
  local/code/modules/atmospherics/machinery/_air_alarm.dm
  local/icons/obj/machine/wallmounts.dmi
  tgstation.dme
Labels: TG Update
