Repository effigy-se/effigy-se, pull requests merged in 2023-07, with the labels that each got.

#297 Effigy Report Issue button
  code/__DEFINES/_effigy/api.dm
  interface/skin.dmf
  local/code/datums/effigy_services.dm
  local/code/modules/client/effigy/bugreport.dm
  tgstation.dme
Labels: Feature, Accessibility

#306 Light Mode
  html/statbrowser.css
  tgui/packages/tgui-panel/styles/main.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
  tgui/packages/tgui-panel/styles/themes/light.scss
  tgui/packages/tgui-panel/themes.js
  tgui/packages/tgui-say/styles/colors.scss
  tgui/packages/tgui/styles/colors.scss
Labels: Test Merge Candidate

#331 Roundstart PDA Scrawls
  code/modules/modular_computers/computers/item/pda.dm
  local/code/modules/client/preferences.dm
  local/code/modules/client/preferences/flavor_text.dm
  local/code/modules/client/preferences_savefile.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/skyrat/species_features.tsx
Labels: Feature

#353 Refactors Species Cable Handling
  code/modules/power/cable.dm
Labels: Balance
