Repository effigy-se/effigy-se, pull requests merged in 2024-02, with the labels that each got.

#685 Effigy UI Palette
  code/__DEFINES/_effigy/DNA.dm
  code/__DEFINES/mobs.dm
  code/modules/client/preferences/sounds.dm
  config/splash_html.txt
  html/statbrowser.css
  interface/skin.dmf
  local/code/modules/client/preferences/body_size.dm
  tgui/packages/tgui-panel/Panel.tsx
  tgui/packages/tgui-panel/chat/ChatTabs.jsx
  tgui/packages/tgui-panel/styles/components/Notifications.scss
  tgui/packages/tgui-panel/styles/components/Ping.scss
  tgui/packages/tgui-panel/styles/main.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/themes.ts
  tgui/packages/tgui-say/styles/colors.scss
  tgui/packages/tgui/constants.ts
  tgui/packages/tgui/interfaces/AiAirlock.jsx
  tgui/packages/tgui/interfaces/PreferencesMenu/Effigy/CharacterPreferenceWindow.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/Effigy/MainPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/age.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/skyrat/genitals.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/ghost_lighting.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/multiz_performance.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/pixel_size.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/skyrat/erp_preferences.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/skyrat/ghost.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/ui_style.tsx
  tgui/packages/tgui/styles/base.scss
  tgui/packages/tgui/styles/colors.scss
  tgui/packages/tgui/styles/components/Button.scss
  tgui/packages/tgui/styles/components/Dropdown.scss
  tgui/packages/tgui/styles/components/Input.scss
  tgui/packages/tgui/styles/components/Knob.scss
  tgui/packages/tgui/styles/components/NoticeBox.scss
  tgui/packages/tgui/styles/components/NumberInput.scss
  tgui/packages/tgui/styles/components/Tabs.scss
Labels: RED LABEL

#697 Fixes FeatureValueInput
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
Labels: Fix

#700 Bluespace RPD
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  local/code/game/objects/items/rcd/RPD.dm
  local/icons/mob/inhands/equipment/tools_lefthand.dmi
  local/icons/mob/inhands/equipment/tools_righthand.dmi
  local/icons/obj/tools.dmi
  tgstation.dme
Labels: Feature, Mirror/Port

#701 Gas miner beacons
  local/code/game/objects/items/devices/summon_beacon.dm
  local/code/modules/cargo/packs/adv_crates.dm
  tgstation.dme
Labels: Feature, Mirror/Port

#702 Engineers have access to airlocks with active fire alarm
  local/code/game/machinery/doors/airlock.dm
  local/code/game/machinery/doors/airlock_override.dm
  local/icons/obj/doors/firedoor_glass.dmi
Labels: Balance

#705 Airlock/status light overlays maintenance
  code/__DEFINES/_effigy/airlock.dm
  code/__DEFINES/colors.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/firealarm.dm
  local/code/game/machinery/doors/airlock.dm
  local/code/game/machinery/doors/airlock_override.dm
  local/code/game/machinery/doors/firedoor.dm
  local/icons/obj/doors/airlocks/abductor/overlays.dmi
  local/icons/obj/doors/airlocks/centcom/overlays.dmi
  local/icons/obj/doors/airlocks/clockwork/overlays.dmi
  local/icons/obj/doors/airlocks/cult/runed/overlays.dmi
  local/icons/obj/doors/airlocks/cult/unruned/overlays.dmi
  local/icons/obj/doors/airlocks/effigy/effigy.dmi
  local/icons/obj/doors/airlocks/effigy/overlays.dmi
  local/icons/obj/doors/airlocks/external/overlays.dmi
  local/icons/obj/doors/airlocks/hatch/overlays.dmi
  local/icons/obj/doors/airlocks/highsec/overlays.dmi
  local/icons/obj/doors/airlocks/shuttle/overlays.dmi
  local/icons/obj/doors/airlocks/station/overlays.dmi
  local/icons/obj/doors/airlocks/tram/tram-overlays.dmi
  local/icons/obj/doors/airlocks/vault/overlays.dmi
  local/icons/obj/doors/firedoor.dmi
  local/icons/obj/doors/firedoor_glass.dmi
Labels: RED LABEL, Test Merge Only

#696 Sigma Octantis
  _maps/map_files/SigmaOctantis/SigmaOctantis.dmm
  _maps/shuttles/arrival_sigmaoctantis.dmm
  _maps/shuttles/emergency_sigmaoctantis.dmm
  _maps/sigma_octantis.json
  code/__DEFINES/_effigy/transport.dm
  config/maps.txt
  local/code/controllers/subsystem/automapper/area_spawn_subsystem.dm
  local/code/datums/shuttles.dm
  local/code/game/area/areas/station.dm
  local/code/game/objects/structures/shower.dm
  local/code/game/objects/structures/watercloset.dm
  local/code/modules/liquids/assets/obj/structures/drains.dmi
  local/code/modules/liquids/liquid_systems/liquid_plumbers.dm
  local/code/modules/liquids/ocean_turfs.dm
  local/code/modules/transport/transport_navigation.dm
  tgstation.dme
Labels: RED LABEL

#726 Sigma - Generic Maint Landmarks
  _maps/map_files/SigmaOctantis/SigmaOctantis.dmm
Labels: FUCK

#723 Emergency shutter water environmental sensors
  code/__DEFINES/_effigy/signals_turf.dm
  code/__DEFINES/_effigy/station.dm
  code/game/machinery/doors/firedoor.dm
  icons/obj/doors/airlocks/shuttle/shuttle.dmi
  local/code/game/machinery/doors/airlock_override.dm
  local/code/game/machinery/doors/firedoor.dm
  local/code/modules/liquids/liquid_systems/liquid_effect.dm
  local/code/modules/liquids/liquid_systems/liquid_turf.dm
  local/icons/obj/doors/airlocks/abductor/overlays.dmi
  local/icons/obj/doors/airlocks/centcom/overlays.dmi
  local/icons/obj/doors/airlocks/clockwork/overlays.dmi
  local/icons/obj/doors/airlocks/cult/runed/overlays.dmi
  local/icons/obj/doors/airlocks/cult/unruned/overlays.dmi
  local/icons/obj/doors/airlocks/effigy/overlays.dmi
  local/icons/obj/doors/airlocks/hatch/overlays.dmi
  local/icons/obj/doors/airlocks/highsec/overlays.dmi
  local/icons/obj/doors/airlocks/multi_tile/public/overlays.dmi
  local/icons/obj/doors/airlocks/shuttle/overlays.dmi
  local/icons/obj/doors/airlocks/tram/tram-half-overlays.dmi
  local/icons/obj/doors/airlocks/tram/tram-overlays.dmi
  local/icons/obj/doors/airlocks/vault/overlays.dmi
  tgstation.dme
Labels: RED LABEL

#735 TG Update 8556e9d
  code/__DEFINES/_effigy/mobs.dm
  code/__DEFINES/mobs.dm
  code/_globalvars/bitfields.dm
  code/datums/components/creamed.dm
  code/game/objects/items/food/meatslab.dm
  code/modules/clothing/under/_under.dm
  code/modules/hydroponics/grown/cereals.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mod/mod_theme.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/dismemberment.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/bodyparts/helpers.dm
  code/modules/surgery/bodyparts/parts.dm
  code/modules/surgery/bodyparts/robot_bodyparts.dm
  code/modules/surgery/bodyparts/species_parts/lizard_bodyparts.dm
  code/modules/surgery/organs/external/_external_organ.dm
  code/modules/surgery/prosthetic_replacement.dm
  html/changelogs/AutoChangeLog-pr-734.yml
  html/changelogs/archive/2024-02.yml
  local/code/game/objects/items.dm
  local/code/modules/client/preferences/mutant_parts.dm
  local/code/modules/clothing/glasses/_glasses.dm
  local/code/modules/clothing/head/_head.dm
  local/code/modules/clothing/masks/_masks.dm
  local/code/modules/lewd/lewd_clothing/shibari_worn_uniform.dm
  local/code/modules/lewd/lewd_items/shibari.dm
  local/code/modules/mob/dead/new_player/sprite_accessories/snout.dm
  local/code/modules/mob/living/carbon/human/custom_bodytype.dm
  local/code/modules/mob/living/carbon/human/species.dm
  local/code/modules/mob/living/emotes/turf_emote.dm
  local/code/modules/mod/modules/_module.dm
  local/code/modules/surgery/bodyparts/mutant/_mutant_bodyparts.dm
  local/code/modules/surgery/bodyparts/mutant/akula_bodyparts.dm
  local/code/modules/surgery/bodyparts/mutant/lizard_bodyparts.dm
  local/code/modules/surgery/bodyparts/mutant/taur_bodyparts.dm
  local/code/modules/surgery/bodyparts/mutant/teshari_bodyparts.dm
  local/code/modules/surgery/bodyparts/mutant/vox_bodyparts.dm
  local/code/modules/surgery/bodyparts/synths/limbs.dm
  local/code/modules/surgery/organs/taur_body.dm
Labels: TG Update
