Repository effigy-se/effigy-se, pull requests merged in 2024-06, with the labels that each got.

#834 New R&D Subjob: Salvaging
  _maps/effigy/map_files/FoxHoleStation/foxholestation.dmm
  _maps/effigy/map_files/RimPoint/RimPoint.dmm
  _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
  local/code/game/area/areas/science.dm
  local/code/game/machinery/scrapbeacon.dm
  local/code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
  local/code/game/objects/structures/scrap.dm
  local/code/modules/mining/ores_coins.dm
  local/code/modules/research/salvage/chunk_tools.dm
  local/code/modules/research/salvage/scrap_chunk.dm
  local/code/modules/research/stock_parts.dm
  local/code/modules/research/stock_parts/stock_part_datum.dm
  local/icons/obj/devices/stock_parts.dmi
  local/icons/obj/machines/scrap_beacon.dmi
  local/icons/obj/salvage.dmi
  local/icons/obj/scrap.dmi
  tgstation.dme
Labels: Feature, Mirror/Port

#836 Revert "New R&D Subjob: Salvaging"
  _maps/effigy/map_files/FoxHoleStation/foxholestation.dmm
  _maps/effigy/map_files/RimPoint/RimPoint.dmm
  _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
  local/code/game/area/areas/science.dm
  local/code/game/machinery/scrapbeacon.dm
  local/code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
  local/code/game/objects/structures/scrap.dm
  local/code/modules/mining/ores_coins.dm
  local/code/modules/research/salvage/chunk_tools.dm
  local/code/modules/research/salvage/scrap_chunk.dm
  local/code/modules/research/stock_parts.dm
  local/code/modules/research/stock_parts/stock_part_datum.dm
  local/icons/obj/devices/stock_parts.dmi
  local/icons/obj/machines/scrap_beacon.dmi
  local/icons/obj/salvage.dmi
  local/icons/obj/scrap.dmi
  tgstation.dme
Labels: FUCK

#468 [TM ONLY] Pass bodies of effigy requests through url_encode
  local/code/datums/effigy_services.dm
Labels: RED LABEL, Test Merge Only
