Repository effigy-se/effigy-se, pull requests merged in 2024-03, with the labels that each got.

#739 Effigy plasma windows
  local/code/game/objects/structures/window.dm
  local/icons/obj/smooth_structures/plasma_window.dmi
  local/icons/obj/smooth_structures/reinforced_window.dmi
  local/icons/obj/smooth_structures/rplasma_window.dmi
Labels: Feature

#740 Fix local logging directory
  code/game/world.dm
Labels: Fix

#742 Fix early return in airlock engineering override
  local/code/game/machinery/doors/airlock_override.dm
Labels: Fix

#743 Orange alert is orange
  local/code/datums/level_datums.dm
  local/icons/obj/firealarm.dmi
Labels: Fix

#746 Lobby HTML adjustments
  local/code/controllers/subsystem/ticker.dm
  local/code/modules/splash/new_player.dm
  local/code/modules/splash/splash_html.dm
Labels: Accessibility, Fix

#748 Better autotransfer logging
  local/code/controllers/subsystem/autotransfer.dm
Labels: Fix

#750 Update Autotransfer
  local/code/controllers/subsystem/autotransfer.dm
Labels: Fix

#753 Sigma Tram Overlay
  _maps/map_files/SigmaOctantis/SigmaOctantis.dmm
  local/code/modules/transport/tram_controller.dm
  local/code/modules/transport/tram_controls.dm
  local/code/modules/transport/tram_displays.dm
  local/code/modules/transport/transport_navigation.dm
  local/icons/obj/machines/computer.dmi
  local/icons/obj/tram/tram_display.dmi
  local/icons/obj/tram/tram_indicator.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/TramControl.tsx
Labels: Feature

#754 Fix digi socks being invisible
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  local/code/modules/client/preferences/middleware/limbs_and_markings.dm
Labels: Fix

#755 Fix antag opt-in preference
  code/_globalvars/_effigy/lists/preferences.dm
  local/code/modules/client/preferences/antag_prefs.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/Effigy/MainPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/antag_target.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/effigy/antag_target.tsx
Labels: Fix

#757 Remove Birbshot from basemaps
  _maps/_basemap.dm
  _maps/birdshot.json
  config/maps.txt
Labels: Cleanup Flagged

#758 Update SideDropdown placement
  tgui/packages/tgui/components/SideDropdown.tsx
Labels: Fix

#759 Update Character Preference window
  tgui/packages/tgui/interfaces/PreferencesMenu/Effigy/CharacterPreferenceWindow.tsx
Labels: Fix

#761 Ready status logging
  code/modules/mob/dead/new_player/new_player.dm
  local/code/modules/mob/dead/new_player/new_player.dm
  local/code/modules/splash/new_player.dm
  tgstation.dme
Labels: Feature

#762 Sigma Octantis webmap
  _maps/map_files/SigmaOctantis/SigmaOctantis.dmm
  html/changelogs/archive/2024-03.yml
  local/code/modules/transport/tram_controller.dm
  local/code/modules/transport/tram_controls.dm
  local/code/modules/transport/tram_displays.dm
  local/interface/interface.dm
  tgui/packages/tgui/interfaces/TramControl.tsx
Labels: Feature, Fix

#764 Remove useless suit voucher
  code/modules/jobs/job_types/shaft_miner.dm
  local/code/modules/mining/seva_obj.dm
  local/code/modules/mining/suit_voucher.dm
  tgstation.dme
Labels: Fix

#769 Trying to fix Sigma's CI
  _maps/shuttles/arrival_sigmaoctantis.dmm
Labels: Needs More Info, FUCK

#772 Subtle notification sound
  local/code/modules/client/preferences/subtle.dm
  local/code/modules/mob/living/emote.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/effigy/subtle.tsx
Labels: Feature

#776 Lo(v)re Wins: Mothic Language return
  local/code/modules/language/canilunzt.dm
  local/code/modules/language/chitinclick.dm
  local/code/modules/language/common.dm
  local/code/modules/language/mothic.dm
  local/code/modules/language/panslavic.dm
  local/code/modules/language/siiktajr.dm
  local/code/modules/language/te_velu_akko.dm
  local/code/modules/language/xerxian.dm
  local/code/modules/language/yangyu.dm
  local/icons/misc/language.dmi
  tgstation.dme
Labels: Mirror/Port

#781 Organs no longer glued to the floor
  code/modules/surgery/organs/organ_movement.dm
Labels: Fix

#775 Firelock water sensor adjustment
  local/code/game/machinery/doors/firedoor.dm
Labels: RED LABEL, Test Merge Only

#777 Oversized
  code/__DEFINES/_effigy/combat.dm
  code/__DEFINES/_effigy/mobs.dm
  code/_globalvars/traits/_traits.dm
  code/_globalvars/traits/admin_tooling.dm
  code/controllers/subsystem/processing/quirks.dm
  code/datums/components/riding/riding_mob.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_movement.dm
  local/code/datums/quirks/neutral_quirks.dm
  local/code/game/machinery/doors/airlock.dm
  local/code/game/machinery/doors/airlock_override.dm
  local/code/game/objects/structures/beds_chairs/chair.dm
  local/code/modules/mob/living/carbon/human/species_types/roundstartslime.dm
  local/code/modules/surgery/organs/stomach.dm
  local/code/modules/vehicles/sealed.dm
  local/icons/obj/medical/organs/stomach.dmi
  local/sound/effects/chair_break.ogg
  tgstation.dme
Labels: Stale, Test Merge Candidate, Mirror/Port

#794 Update interaction preferences
  local/code/modules/client/preferences/erp_preferences.dm
Labels: Fix

#796 Update headshot regex
  local/code/modules/client/preferences/headshot.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/skyrat/headshot.tsx
Labels: Accessibility
