Repository effigy-se/effigy-se, pull requests merged in 2024-07, with the labels that each got.

#843 Update webmap
  local/interface/interface.dm
Labels: Fix

#845 Update DNA Fixer
  local/code/game/machinery/dna_fixer.dm
Labels: Fix

#847 Fix DNA Fixer icon
  local/icons/obj/medical/dna_fixer.dmi
Labels: Fix

#844 Fix tram lights
  local/code/game/machinery/doors/airlock.dm
  local/icons/obj/doors/airlocks/tram/tram-half-overlays.dmi
Labels: Fix

#855 Fixes transfer vote
  local/code/datums/transfer_vote.dm
Labels: Fix

#869 Fixes large hypospray
  local/code/modules/reagents/reagent_containers/hypospray.dm
Labels: Fix

#875 TG Update 6cad13d
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/dcs/signals/signals_xeno_control.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/research/slimes.dm
  code/_globalvars/lists/names.dm
  code/_onclick/click.dm
  code/_onclick/click_alt.dm
  code/_onclick/click_ctrl.dm
  code/datums/ai/oldhostile/hostile_tameable.dm
  code/datums/components/pet_commands/obeys_commands.dm
  code/datums/components/rotation.dm
  code/datums/components/style/style_meter.dm
  code/datums/components/toggle_suit.dm
  code/datums/components/trapdoor.dm
  code/datums/elements/openspace_item_click_handler.dm
  code/datums/id_trim/outfits.dm
  code/datums/storage/storage.dm
  code/game/objects/items.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/holosign_creator.dm
  code/game/objects/items/rcd/RCD.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/modules/antagonists/space_dragon/carp_rift.dm
  code/modules/bitrunning/components/avatar_connection.dm
  code/modules/bitrunning/server/obj_generation.dm
  code/modules/client/preferences/names.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/basic/guardian/guardian_types/support.dm
  code/modules/mob/living/basic/slime/life.dm
  code/modules/mob/living/basic/space_fauna/revenant/_revenant.dm
  code/modules/mob/living/basic/space_fauna/space_dragon/space_dragon.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/research/techweb/_techweb.dm
  code/modules/research/techweb/nodes/security_nodes.dm
  code/modules/research/techweb/nodes/syndicate_nodes.dm
  code/modules/research/xenobiology/xenobio_camera.dm
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_mammal_slugcat.png
  code/modules/wiremod/shell/controller.dm
  html/changelogs/archive/2024-07.yml
  icons/mob/huds/hud.dmi
  strings/names/hackers.txt
  tgui/packages/tgui/interfaces/Orbit/OrbitContent.tsx
Labels: TG Update

#878 Fix map lints (telescreen)
  _maps/effigy/map_files/FoxHoleStation/foxholestation.dmm
  _maps/effigy/map_files/RimPoint/RimPoint.dmm
  _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
  _maps/effigy/templates/automapper/birdshot/birdshot_broadcast_studio.dmm
  _maps/effigy/templates/automapper/icebox/icebox_broadcast_studio.dmm
  _maps/effigy/templates/automapper/metastation/metastation_broadcast_studio.dmm
  _maps/effigy/templates/automapper/northstar/northstar_broadcast_studio.dmm
  _maps/effigy/templates/automapper/tramstation/tramstation_broadcast_studio.dmm
  local/code/game/machinery/computer/camera.dm
Labels: Fix

#885 Fixes Maploaded Liquid Plumbers
  _maps/effigy/map_files/FoxHoleStation/foxholestation.dmm
  _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
  _maps/effigy/templates/automapper/automapper_config.toml
  _maps/effigy/templates/automapper/metastation/metastation_cryo.dmm
  local/code/modules/liquids/liquid_systems/liquid_plumbers.dm
Labels: Fix, FUCK
