Repository effigy-se/effigy-se, pull requests merged in 2024-01, with the labels that each got.

#650 Character Directory
  code/__DEFINES/_effigy/preferences.dm
  code/controllers/subsystem/ticker.dm
  code/modules/mob/living/carbon/human/examine.dm
  local/code/datums/character_directory.dm
  local/code/modules/client/character_directory.dm
  local/code/modules/client/preferences/_preference.dm
  local/code/modules/mob/living/examine_tgui.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/CharacterDirectory.jsx
  tgui/packages/tgui/interfaces/ExaminePanel.jsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/effigy/character_directory.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/effigy/character_directory.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/effigy/obscure_on_examine.tsx
Labels: Feature, Mirror/Port

#665 Fix autotransfer calling a vote when a delayed round starts
  local/code/controllers/subsystem/autotransfer.dm
Labels: Fix

#666 Lobby music v1
  code/_globalvars/_effigy/config.dm
  code/controllers/subsystem/ticker.dm
  local/code/modules/lobby_music/lobby_music.dm
  tgstation.dme
Labels: Feature

#670 Fix felinid tail selection
  code/modules/mob/living/carbon/human/_species.dm
  local/code/modules/mob/living/human/species.dm
Labels: Fix

#663 Whitelist in-game TGUI notification
  code/__DEFINES/_effigy/admin.dm
  code/_globalvars/_effigy/config.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/ooc.dm
  local/code/datums/effigy_registration.dm
  local/code/modules/client/effigy_registration.dm
  local/code/modules/splash/new_player.dm
  tgstation.dme
  tgui/packages/tgui-panel/themes.ts
  tgui/packages/tgui/interfaces/EffigyAccountRestricted.tsx
Labels: RED LABEL, Test Merge Only

#677 Changes default_mutant_bodyparts list to be index based
  code/__DEFINES/_effigy/DNA.dm
  code/__DEFINES/_effigy/mobs.dm
  code/__HELPERS/_effigy/global_lists.dm
  local/code/modules/client/preferences.dm
  local/code/modules/mob/living/carbon/human/species.dm
  local/code/modules/mob/living/carbon/human/species_types/aquatic.dm
  local/code/modules/mob/living/carbon/human/species_types/ghoul.dm
  local/code/modules/mob/living/carbon/human/species_types/humanoid.dm
  local/code/modules/mob/living/carbon/human/species_types/insect.dm
  local/code/modules/mob/living/carbon/human/species_types/lizard.dm
  local/code/modules/mob/living/carbon/human/species_types/mammal.dm
  local/code/modules/mob/living/carbon/human/species_types/monkey.dm
  local/code/modules/mob/living/carbon/human/species_types/moth.dm
  local/code/modules/mob/living/carbon/human/species_types/podweak.dm
  local/code/modules/mob/living/carbon/human/species_types/roundstartslime.dm
  local/code/modules/mob/living/carbon/human/species_types/skrell.dm
  local/code/modules/mob/living/carbon/human/species_types/synthetic.dm
  local/code/modules/mob/living/carbon/human/species_types/tajaran.dm
  local/code/modules/mob/living/carbon/human/species_types/unathi.dm
  local/code/modules/mob/living/carbon/human/species_types/vox.dm
  local/code/modules/mob/living/carbon/human/species_types/vulpkanin.dm
  local/code/modules/mob/living/carbon/human/species_types/xeno.dm
Labels: Fix

#683 Fix big (ass) slappy
  local/code/modules/mob/living/carbon/carbon_defense.dm
  tgstation.dme
Labels: Fix

#687 The Portening: Module Mirrors, Functionality, Oh My
  _maps/map_files/FoxHoleStation/foxholestation.dmm
  code/modules/surgery/bodyparts/dismemberment.dm
  local/code/datums/loadouts/loadout_datum_glasses.dm
  local/code/datums/loadouts/loadout_datum_suit.dm
  local/code/datums/loadouts/loadout_datum_under.dm
  local/code/modules/clothing/glasses/_glasses.dm
  local/code/modules/lewd/lewd_machinery/lustwish.dm
  local/code/modules/liquids/liquid_systems/liquid_controller.dm
  local/code/modules/liquids/liquid_systems/liquid_turf.dm
  local/code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  local/code/modules/surgery/bodyparts/synths/brain.dm
  local/code/modules/surgery/bodyparts/synths/eyes.dm
  local/code/modules/surgery/bodyparts/synths/internal_computer/internal_computer.dm
  local/code/modules/surgery/bodyparts/synths/power_cord.dm
  local/code/modules/surgery/bodyparts/synths/tongue.dm
  local/code/modules/vending/clothesmate.dm
  local/icons/obj/mob/mutant/mutant_accessories/tails.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/LoadoutManager.tsx
Labels: Feature, Fix, Mirror/Port

#692 TG Update da1b76a
  _maps/map_files/Birdshot/birdshot.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/modules/transport/tram/tram_controller.dm
  code/modules/transport/tram/tram_controls.dm
  code/modules/transport/tram/tram_power.dm
  code/modules/transport/tram/tram_signals.dm
  code/modules/transport/transport_module.dm
  html/changelogs/archive/2024-01.yml
  icons/obj/tram/tram_controllers.dmi
  tgstation.dme
Labels: TG Update

#691 [PORT] Wizard balance changes
  code/modules/antagonists/wizard/equipment/wizard_spellbook.dm
  code/modules/mob/living/basic/bots/medbot/medbot.dm
  code/modules/spells/spell_types/right_and_wrong.dm
  local/code/modules/antagonist/wizard/spellbook_entries.dm
  local/code/modules/antagonist/wizard/wizard_events.dm
  local/code/modules/antagonist/wizard/wizard_items.dm
  local/code/modules/antagonist/wizard/wizard_spells.dm
  tgstation.dme
Labels: Mirror/Port
