Repository effigy-se/effigy-se, pull requests merged in 2024-04, with the labels that each got.

#803 One Idiot Tries to Fix the OpenDream-Specific Lints
  code/modules/mod/mod_control.dm
  local/code/modules/mob/living/carbon/human/human.dm
  local/code/modules/mob/living/emotes/turf_emote.dm
Labels: Fix

#811 Creates a node compatibility mode (#82334)
  dependencies.sh
  tgui/.prettierignore
  tools/bootstrap/node
  tools/bootstrap/node_.ps1
Labels: TG Update

#814 Implements An Unused Sprite From 2021
  local/code/modules/lewd/lewd_items/_erp_disabled_item_enforcement.dm
  local/code/modules/lewd/lewd_items/leash.dm
  local/code/modules/lewd/lewd_machinery/lustwish.dm
  tgstation.dme
Labels: Feature
