Repository effigy-se/effigy-se, pull requests merged in 2024-08, with the labels that each got.

#910 Fix duplicate manifest entries
  code/modules/mob/dead/new_player/new_player.dm
Labels: Fix

#913 Update runechat color defines
  local/code/modules/client/preferences/chat_color.dm
Labels: Fix

#896 Medical technician bag [TM ONLY]
  local/code/game/objects/items/storage/satchel.dm
  local/code/modules/cargo/packs/adv_crates.dm
  local/icons/mob/inhands/medical/cases_lefthand.dmi
  local/icons/mob/inhands/medical/cases_righthand.dmi
  local/icons/mob/medical/worn.dmi
  local/icons/mob/medical/worn_teshari.dmi
  local/icons/obj/medical/storage.dmi
  tgstation.dme
Labels: RED LABEL

#915 [LOL] Unfucks Luna's Energy Upgrade So It Actually Works
  local/code/modules/mapfluff/ruins/jungle_ruin_code.dm
Labels: FUCK, Oversight

#935 [PORT] GAGS Maid Outfit
  local/code/datums/greyscale/greyscale_configs.dm
  local/code/datums/greyscale/json_configs/costumes/maid_arm_covers.json
  local/code/datums/greyscale/json_configs/costumes/maid_costume.json
  local/code/datums/greyscale/json_configs/costumes/maid_headband.json
  local/code/datums/greyscale/json_configs/costumes/maid_neck_cover.json
  local/code/datums/loadouts/loadout_datum_gloves.dm
  local/code/datums/loadouts/loadout_datum_heads.dm
  local/code/datums/loadouts/loadout_datum_neck.dm
  local/code/datums/loadouts/loadout_datum_under.dm
  local/code/modules/clothing/hands/hands.dm
  local/code/modules/clothing/head/costume.dm
  local/code/modules/clothing/neck/_neck.dm
  local/code/modules/clothing/under/costume.dm
  local/code/modules/vending/autodrobe.dm
  local/icons/mob/clothing/greyscale_clothing/maid_costume_worn.dmi
  local/icons/obj/clothing/greyscale_clothing/maid_costume.dmi
Labels: Mirror/Port

#934 Condo System
  _maps/effigy/map_files/RimPoint/RimPoint.dmm
  _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
  _maps/effigy/map_files/generic/CentCom_z2_effigy.dmm
  _maps/effigy/shuttles/emergency_foxhole.dmm
  _maps/effigy/templates/condos/alleyway.dmm
  _maps/effigy/templates/condos/beach_condo.dmm
  _maps/effigy/templates/condos/dsthree_condo.dmm
  _maps/effigy/templates/condos/foxhole_chapel.dmm
  _maps/effigy/templates/condos/gm_condo.dmm
  _maps/effigy/templates/condos/hilbertshotel.dmm
  _maps/effigy/templates/condos/holestation_bridge.dmm
  _maps/effigy/templates/condos/lodge_pool.dmm
  _maps/effigy/templates/condos/manor_hall.dmm
  _maps/effigy/templates/condos/medieval_bog.dmm
  _maps/effigy/templates/condos/necropolis.dmm
  _maps/effigy/templates/condos/northstar_dorms_four.dmm
  _maps/effigy/templates/condos/ocean_view.dmm
  _maps/effigy/templates/condos/planar_soil.dmm
  _maps/effigy/templates/condos/sigma_lux_dorm.dmm
  _maps/effigy/templates/condos/station_arrivals.dmm
  _maps/effigy/templates/condos/xeno_resin.dmm
  code/__DEFINES/_effigy/maps.dm
  code/game/objects/items/blueprints.dm
  code/modules/mapfluff/ruins/spaceruin_code/hilbertshotel.dm
  local/code/game/objects/structures/beds_chairs/sofa.dm
  local/code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  local/code/game/objects/structures/fluff.dm
  local/code/modules/condos/condo_area.dm
  local/code/modules/condos/condo_doors.dm
  local/code/modules/condos/condo_reservation.dm
  local/code/modules/condos/condo_subsystem.dm
  local/code/modules/condos/condo_teleporter.dm
  local/code/modules/condos/condo_templates.dm
  local/icons/obj/fluff/general.dmi
  tgstation.dme
  tools/icon_cutter/check.py
Labels: Feature, Test Merge Candidate, RED LABEL
