Repository effigy-se/effigy-se, pull requests merged in 2025-01, with the labels that each got.

#1002 E++ - A Few More Descriptions; Futureproofing
  code/__DEFINES/_effigy/examine_defines.dm
  local/code/game/objects/items/storage/fancy.dm
  local/code/game/objects/items/toys.dm
  local/code/modules/cards/deck/deck.dm
  local/code/modules/mob/living/brain/MMI.dm
  tgstation.dme
Labels: Stale, Stale-b-gone

#1004 [FUCK] CI Fix
  code/__DEFINES/_effigy/examine_defines.dm
  local/code/game/objects/items/storage/fancy.dm
  local/code/game/objects/items/toys.dm
  local/code/modules/cards/deck/deck.dm
  local/code/modules/mob/living/brain/MMI.dm
Labels: FUCK

#1006 Add box of gas miner beacons to CE's locker
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Labels: Stale

#1015 Backports Nova Sector #4188
  local/code/modules/clothing/neck/collars.dm
  local/code/modules/lewd/lewd_clothing/kink_collars.dm
  local/code/modules/lewd/lewd_clothing/shockcollar.dm
Labels: Mirror/Port
