Repository effigy-se/effigy-se, pull requests merged in 2025-02, with the labels that each got.

#1016 Reverts "Reverts "New R&D Subjob: Salvaging""
  _maps/effigy/map_files/FoxHoleStation/foxholestation.dmm
  _maps/effigy/map_files/RimPoint/RimPoint.dmm
  _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
  local/code/game/area/areas/science.dm
  local/code/game/machinery/scrapbeacon.dm
  local/code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
  local/code/game/objects/structures/scrap.dm
  local/code/modules/mining/ores_coins.dm
  local/code/modules/research/salvage/chunk_tools.dm
  local/code/modules/research/salvage/scrap_chunk.dm
  local/code/modules/research/stock_parts.dm
  local/code/modules/research/stock_parts/stock_part_datum.dm
  local/icons/obj/devices/stock_parts.dmi
  local/icons/obj/machines/scrap_beacon.dmi
  local/icons/obj/salvage.dmi
  local/icons/obj/scrap.dmi
  tgstation.dme
Labels: Feature, Mirror/Port

#1017 Salvage Rebalance
  _maps/effigy/map_files/FoxHoleStation/foxholestation.dmm
  _maps/effigy/map_files/RimPoint/RimPoint.dmm
  _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
  local/code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
  local/code/modules/research/designs/machine_designs.dm
  local/code/modules/research/salvage/chunk_tools.dm
  local/code/modules/research/salvage/scrap_chunk.dm
  local/code/modules/research/salvage/scrap_compactor.dm
  local/code/modules/research/salvage/scrap_items/_scrap.dm
  local/code/modules/research/salvage/scrap_items/apparatus.dm
  local/code/modules/research/salvage/scrap_items/gacha_ball.dm
  local/code/modules/research/salvage/scrap_items/tattered_sheet_metal.dm
  local/code/modules/research/salvage/scrap_items/toilet_paper.dm
  local/code/modules/research/salvage/scrap_items/toy_robot.dm
  local/code/modules/research/salvage/scrap_items/whoopie_cushion.dm
  local/code/modules/research/salvage/scrap_items/yield_sign.dm
  local/code/modules/research/techweb/research_nodes.dm
  local/icons/mob/inhands/scrap_lefthand.dmi
  local/icons/mob/inhands/scrap_righthand.dmi
  local/icons/obj/machines/scrap_compactor.dmi
  local/icons/obj/scrap.dmi
  tgstation.dme
Labels: Feature

#982 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/topic.dm
  code/modules/tgs/v5/undefs.dm
Labels: Tools
